// Generate OpenAPI 3.1 spec from scraped Flowhub Markdown docs.
//
// Usage:
//   ANTHROPIC_API_KEY=sk-... DOCS_DIR=../flowhub-api-docs node generate-spec.js
//
// Reads the per-section files in $DOCS_DIR/sections/ and the manifest, asks
// Claude to draft an OpenAPI 3.1 spec from each endpoint-bearing section,
// merges the results, validates, and writes:
//   $DOCS_DIR/spec/openapi.yaml
//   $DOCS_DIR/spec/openapi.json
//   $DOCS_DIR/spec/postman-collection.json
//   $DOCS_DIR/spec/README.md  (with prominent "AI-generated, not authoritative" disclaimer)
//
// IMPORTANT: The output is an approximation. Flowhub publishes their docs in
// human-readable prose with examples, not in machine-precise schema form.
// Claude infers types from descriptions and examples, which means subtle
// inaccuracies are possible. Always treat this as a starting point, not an
// authoritative source.

import Anthropic from "@anthropic-ai/sdk";
import { Converter as PostmanConverter } from "openapi-to-postmanv2";
import YAML from "yaml";
import fs from "node:fs/promises";
import path from "node:path";

const DOCS_DIR = path.resolve(process.env.DOCS_DIR || "../flowhub-api-docs");
const SECTIONS_DIR = path.join(DOCS_DIR, "sections");
const SPEC_DIR = path.join(DOCS_DIR, "spec");
const MANIFEST_PATH = path.join(DOCS_DIR, "manifest.json");

const MODEL = "claude-opus-4-7";
const MAX_TOKENS = 16_000;

// Sections that contain endpoint definitions (not just prose like overview/conventions)
const ENDPOINT_SECTION_PATTERN = /^(03|04|05|06|07|08|09|10|11|12|99)-/;

const SYSTEM_PROMPT = `You are an OpenAPI 3.1 specification generator. You will receive scraped Markdown documentation for a section of an API and must produce a JSON object containing the OpenAPI \`paths\` and \`components.schemas\` fragments for that section.

Rules:
1. Output ONLY a single JSON object, no prose, no code fences. Start with { and end with }.
2. Top-level keys must be exactly "paths" and "schemas". "paths" follows OpenAPI 3.1 paths-object shape. "schemas" follows OpenAPI 3.1 schemas-object shape (the contents of components.schemas).
3. For every endpoint you can identify in the docs, include: method, path, operationId, summary, description, parameters (with name, in, required, schema, description), requestBody (if applicable), responses (status code -> response object with content -> application/json -> schema).
4. Reference reusable types via $ref to "#/components/schemas/Name". Define those schemas in the "schemas" object.
5. When a parameter or field's type is unclear from the docs, infer it from any example values shown. If still unclear, use "string" with a description noting the ambiguity.
6. When response examples are present, use them to construct accurate schemas. Include the example in the schema's "example" field.
7. Use snake_case or camelCase for operationIds based on what the docs show in URL paths. Be consistent within a section.
8. Do NOT invent endpoints not in the docs. Do NOT invent fields not shown.
9. If the section contains no endpoint definitions (e.g. it's all prose), return {"paths": {}, "schemas": {}}.

Output JSON only.`;

async function generateForSection(client, sectionName, sectionMarkdown) {
  console.log(`[${sectionName}] requesting OpenAPI fragments...`);
  const response = await client.messages.create({
    model: MODEL,
    max_tokens: MAX_TOKENS,
    system: SYSTEM_PROMPT,
    messages: [
      {
        role: "user",
        content: `Section: ${sectionName}\n\n---\n\n${sectionMarkdown}`,
      },
    ],
  });

  const text = response.content
    .filter((b) => b.type === "text")
    .map((b) => b.text)
    .join("");

  // Strip any accidental fences
  const cleaned = text.replace(/^```(json)?\n?/, "").replace(/\n?```$/, "").trim();

  try {
    return JSON.parse(cleaned);
  } catch (err) {
    console.error(`[${sectionName}] JSON parse failed; saving raw response for debugging`);
    await fs.mkdir(SPEC_DIR, { recursive: true });
    await fs.writeFile(
      path.join(SPEC_DIR, `_debug_${sectionName}.txt`),
      text,
      "utf8"
    );
    return { paths: {}, schemas: {} };
  }
}

function mergeSpecs(fragments, manifest) {
  const paths = {};
  const schemas = {};

  for (const fragment of fragments) {
    Object.assign(paths, fragment.paths || {});
    Object.assign(schemas, fragment.schemas || {});
  }

  return {
    openapi: "3.1.0",
    info: {
      title: "Flowhub API (Unofficial)",
      version: manifest.scraped_at?.split("T")[0] || "0.0.0",
      description: [
        "**UNOFFICIAL, AI-GENERATED APPROXIMATION.**",
        "",
        "This OpenAPI spec was generated by an LLM from scraped human-readable documentation at " +
          (manifest.source || "https://flowhub.stoplight.io") +
          ". It is not produced or endorsed by Flowhub, Inc.",
        "",
        "It may contain inaccuracies in types, required-flags, or schema shapes. Always verify against the authoritative source before using in production.",
        "",
        "Source: https://github.com/yerba-buena/flowhub-api-docs",
      ].join("\n"),
      contact: {
        name: "Yerba Buena Brands, LLC",
        url: "https://github.com/yerba-buena/flowhub-api-docs/issues",
      },
      license: {
        name: "Disclaimer",
        url: "https://github.com/yerba-buena/flowhub-api-docs/blob/main/DISCLAIMER.md",
      },
    },
    servers: [
      {
        url: "https://api.flowhub.com",
        description: "Production (verify against official docs before use)",
      },
    ],
    paths,
    components: { schemas },
  };
}

async function generatePostman(openapi) {
  return new Promise((resolve, reject) => {
    PostmanConverter.convert(
      { type: "json", data: openapi },
      { folderStrategy: "Tags" },
      (err, result) => {
        if (err) return reject(err);
        if (!result.result) return reject(new Error(result.reason || "conversion failed"));
        resolve(result.output[0].data);
      }
    );
  });
}

async function main() {
  if (!process.env.ANTHROPIC_API_KEY) {
    console.error("ERROR: ANTHROPIC_API_KEY env var is required");
    process.exit(1);
  }

  await fs.mkdir(SPEC_DIR, { recursive: true });

  const manifest = JSON.parse(await fs.readFile(MANIFEST_PATH, "utf8"));
  console.log(`[load] manifest: ${manifest.successful} pages across ${manifest.sections.length} sections`);

  const sectionFiles = await fs.readdir(SECTIONS_DIR);
  const endpointSections = sectionFiles
    .filter((f) => f.endsWith(".md") && ENDPOINT_SECTION_PATTERN.test(f))
    .sort();

  console.log(`[plan] processing ${endpointSections.length} endpoint sections`);

  const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  const fragments = [];

  for (const filename of endpointSections) {
    const md = await fs.readFile(path.join(SECTIONS_DIR, filename), "utf8");
    const sectionName = filename.replace(/\.md$/, "");
    try {
      const fragment = await generateForSection(client, sectionName, md);
      fragments.push(fragment);
      console.log(
        `[${sectionName}] -> ${Object.keys(fragment.paths || {}).length} paths, ${Object.keys(fragment.schemas || {}).length} schemas`
      );
    } catch (err) {
      console.error(`[${sectionName}] failed: ${err.message}`);
    }
  }

  const spec = mergeSpecs(fragments, manifest);
  const yamlOut = YAML.stringify(spec);
  const jsonOut = JSON.stringify(spec, null, 2);

  await fs.writeFile(path.join(SPEC_DIR, "openapi.yaml"), yamlOut, "utf8");
  await fs.writeFile(path.join(SPEC_DIR, "openapi.json"), jsonOut, "utf8");
  console.log(`[write] openapi.yaml (${yamlOut.length} chars), openapi.json`);

  try {
    const postman = await generatePostman(spec);
    await fs.writeFile(
      path.join(SPEC_DIR, "postman-collection.json"),
      postman,
      "utf8"
    );
    console.log(`[write] postman-collection.json`);
  } catch (err) {
    console.error(`[postman] conversion failed: ${err.message}`);
  }

  const specReadme = `# OpenAPI / Postman Spec Exports

> **⚠️ AI-GENERATED APPROXIMATION — NOT AUTHORITATIVE**
>
> The files in this directory were generated by an LLM (Claude) from
> scraped human-readable documentation. They are NOT produced or endorsed
> by Flowhub, Inc., and they may contain inaccuracies in field types,
> required flags, schema shapes, or endpoint coverage.
>
> **Always verify against the authoritative source** at
> https://flowhub.stoplight.io/ before using these files for any
> production purpose.

## Files

| File | Description |
|------|-------------|
| \`openapi.yaml\` | OpenAPI 3.1 spec, YAML format |
| \`openapi.json\` | OpenAPI 3.1 spec, JSON format |
| \`postman-collection.json\` | Postman Collection v2.1 |

## How these were generated

The scraper at https://github.com/yerba-buena/flowhub-api-docs-scraper
mirrors the Flowhub portal as Markdown. Then \`generate-spec.js\` reads the
per-section Markdown files and asks Claude to produce OpenAPI fragments for
each section, merges them, and converts to Postman.

## Importing into Insomnia

Insomnia natively imports OpenAPI 3.1. Use \`openapi.yaml\` directly —
File → Import → From File.

## Importing into Postman

Use \`postman-collection.json\` directly. File → Import.

## Regenerating

From the scraper repo:

\`\`\`bash
ANTHROPIC_API_KEY=sk-... DOCS_DIR=../flowhub-api-docs npm run generate-spec
\`\`\`

## Reporting inaccuracies

If you spot a wrong type or missing endpoint, please open an issue at
https://github.com/yerba-buena/flowhub-api-docs/issues. Include the
endpoint, the spec's claim, and the correct shape from the live docs.
`;

  await fs.writeFile(path.join(SPEC_DIR, "README.md"), specReadme, "utf8");
  console.log(`[write] spec/README.md`);
  console.log(`\nDone. Spec exports in ${SPEC_DIR}`);
}

main().catch((err) => {
  console.error("fatal:", err);
  process.exit(1);
});
